version: '3.3'

services:
  postgres:
    container_name: postgres_con
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB

    volumes:
      - postgres_data:/var/lib/postgresql/data

    image: postgres

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/marinosnisiotis/Desktop/spring-boot/docker-postgres-container-data'