version: '3.3'

services:
  postgres:
    container_name: postgres_con
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB

    volumes:
      - /Users/marinosnisiotis/Desktop/spring-boot/docker-postgres-container-data:/var/lib/postgresql/data

    image: postgres